### ISSUE TITLE
Task 2: Experience with GitHub & Git

### ISSUE THREAD

**Issue by rongweiji** [livingspring/GSoC-pgRouting#1]
- [x] Fork the [GSoC-pgRouting](https://github.com/pgRouting/GSoC-pgRouting) repository
- [x] activate issues in your fork
- [x] open an issue in your fork and put this content on the issue
- [x] Clone your fork repository in your computer
- [x] Create remote named `upstream` pointing to https://github.com/pgRouting/GSoC-pgRouting
- [x] checkout to the `develop` branch of `upstream`
- [x] create new branch with name `<your-git-nick>-test`
- [x] Edit `doc/src/pgRouting-introduction.rst` and put your name on contributor
- [x] push the newly created branch with the change 
- [x] Create a pull request to https://github.com/pgRouting/GSoC-pgRouting
- [x] put link of the PR and of the issue on a comment on the issue you created on [GSoC-pgRouting](https://github.com/pgRouting/GSoC-pgRouting) repository

**Comment by rongweiji** [comment]
# Task 2 Done
https://github.com/pgRouting/GSoC-pgRouting/pull/362
